-- MySQL Script generated by MySQL Workbench
-- Sat Oct 12 08:49:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema creat6ky_english_connect_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instructor` ;

CREATE TABLE IF NOT EXISTS `instructor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_on` TIMESTAMP(6) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'active',
  PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course` ;

CREATE TABLE IF NOT EXISTS `course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `level` INT NULL,
  `day` VARCHAR(45) NULL,
  `time` VARCHAR(45) NULL,
  `year` VARCHAR(45) NULL,
  `building` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_on` TIMESTAMP(6) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'active',
  `instructor_id` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student` ;

CREATE TABLE IF NOT EXISTS `student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_on` TIMESTAMP(6) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'active',
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendance` ;

CREATE TABLE IF NOT EXISTS `attendance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `attendance_value` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_on` TIMESTAMP(6) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'active',
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id`));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
