-- MySQL Script generated by MySQL Workbench
-- Wed Oct  2 20:44:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema creat6ky_english_connect_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instructor` ;

CREATE TABLE IF NOT EXISTS `instructor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(6) NULL,
  `modified_on` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course` ;

CREATE TABLE IF NOT EXISTS `course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `level` INT NULL,
  `day` VARCHAR(45) NULL,
  `time` VARCHAR(45) NULL,
  `year` VARCHAR(45) NULL,
  `building` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(6) NULL,
  `modified_on` TIMESTAMP(6) NULL,
  `instructor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_course_instructor1`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `instructor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student` ;

CREATE TABLE IF NOT EXISTS `student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(6) NULL,
  `modified_on` TIMESTAMP(6) NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_student_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendance` ;

CREATE TABLE IF NOT EXISTS `attendance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `attendance_value` VARCHAR(45) NULL,
  `created_at` TIMESTAMP(6) NULL,
  `modified_on` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `student_has_attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student_has_attendance` ;

CREATE TABLE IF NOT EXISTS `student_has_attendance` (
  `student_id` INT NOT NULL,
  `attendance_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `attendance_id`),
  CONSTRAINT `fk_student_has_attendance_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_attendance_attendance1`
    FOREIGN KEY (`attendance_id`)
    REFERENCES `attendance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
